In [1]:
import numpy as np

In [2]:
x=np.random.randint(1,100,10)

In [3]:
x

array([44, 10, 21, 85, 99,  9, 89, 25, 12, 59])

In [4]:
x2=[]
for i in x:
    if i<50:
        x2.append(i)
print(x2)

[44, 10, 21, 9, 25, 12]


In [7]:
x<50

array([ True,  True,  True, False, False,  True, False,  True,  True,
       False])

# masking

In [10]:
x[x<50]

array([44, 10, 21,  9, 25, 12])